# Generated by Django 6.0.4 on 2026-06-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0019_alter_paymentinstruction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.userprofile',),
        ),
    ]
