# Generated by Django 6.0.4 on 2026-07-12 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('full_name', models.CharField(blank=True, default='', max_length=160)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('bio', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_institution', models.CharField(blank=True, default='', max_length=180)),
                ('teacher_subject', models.CharField(blank=True, default='', max_length=120)),
                ('teacher_experience_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('assigned_categories', models.ManyToManyField(blank=True, help_text='Categories that this teacher is allowed to manage.', related_name='assigned_teachers', to='content.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher profile',
                'verbose_name_plural': 'Teacher profiles',
                'ordering': ['user__email'],
            },
        ),
    ]
