# Generated by Django 6.0.4 on 2026-07-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
    ]
