# Generated by Django 6.0.4 on 2026-07-02 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0002_teacherprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
