# Generated by Django 6.0.4 on 2026-07-07 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_courses', to='teacher_dashboard.teacherprofile'),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='content.course'),
        ),
        migrations.AddField(
            model_name='coursecertificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.course'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursequizquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.coursequiz'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='content.lesson'),
        ),
        migrations.AddField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='content.course'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.module'),
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_quizzes', to='content.module'),
        ),
        migrations.AddField(
            model_name='passwordresetsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to='content.course'),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='content.coursequiz'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category'),
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.subcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecertificate',
            unique_together={('user', 'course')},
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'status'], name='content_cou_user_id_c935b5_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['course', 'status'], name='content_cou_course__f998d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='uniq_enrollment_per_user_course'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'is_used', 'expires_at'], name='content_ema_user_id_05a6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['lesson', 'order'], name='content_les_lesson__aeba6e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['lesson', 'content_type', 'order'], name='content_les_lesson__0e9f15_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['lesson', 'is_published', 'order'], name='content_les_lesson__f4dd6b_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonresource',
            constraint=models.UniqueConstraint(fields=('lesson', 'slug'), name='uniq_resource_slug_per_lesson'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['course', 'order'], name='content_mod_course__07037a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('course', 'slug')},
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'order'], name='content_les_module__c210ff_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['module', 'is_published', 'order'], name='content_les_module__dffc17_idx'),
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='uniq_lesson_slug_per_module'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['lesson', 'is_active'], name='content_cou_lesson__7adaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='coursequiz',
            index=models.Index(fields=['module', 'is_active'], name='content_cou_module__33370f_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['course', 'status', 'submitted_at'], name='content_pay_course__82b52b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['user', 'status', 'submitted_at'], name='content_pay_user_id_05b417_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentsubmission',
            index=models.Index(fields=['transaction_id'], name='content_pay_transac_8cbe04_idx'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['user', 'submitted_at'], name='content_qui_user_id_58b769_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
