# Generated by Django 6.0.4 on 2026-07-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequizquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursequizquestion',
            name='explanation_image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_explanations/'),
        ),
        migrations.AddField(
            model_name='coursequizquestion',
            name='explanation_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursequizquestion',
            name='explanation_video_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='coursequizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_questions/'),
        ),
    ]
