# Generated by Django 6.0.4 on 2026-06-22 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
