# Generated by Django 6.0.4 on 2026-07-09 08:32

from django.db import migrations, models


def _normalize_blank_contacts(apps, schema_editor):
    User = apps.get_model("content", "User")
    User.objects.filter(email="").update(email=None)
    User.objects.filter(phone_number="").update(phone_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('content', '0004_payment_submission_bkash_phone_and_other_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(_normalize_blank_contacts, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='user_must_have_email_or_phone'),
        ),
    ]
