# Generated by Django 6.0.4 on 2026-06-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_covers/"),
        ),
    ]
