# Generated by Django 6.0.4 on 2026-06-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_course_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="enrollment_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="course",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
