# Generated by Django 6.0.4 on 2026-07-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_user_email_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='content_ema_user_id_05a6dd_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetsession',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='user_must_have_email_or_phone',
        ),
        migrations.AlterField(
            model_name='paymentinstruction',
            name='payment_method_name',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], default='other', max_length=20),
        ),
        migrations.RemoveField(
            model_name='emailotp',
            name='user',
        ),
        migrations.DeleteModel(
            name='PasswordResetSession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
