# Generated by Django 6.0.4 on 2026-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_course_enrollment_count_is_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
