# Generated by Django 6.0.4 on 2026-06-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_subcategory_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
