# Generated by Django 6.0.4 on 2026-06-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_module_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
