# Generated by Django 6.0.4 on 2026-06-26 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_remove_lesson_duration_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='coursecontent',
            name='content_cou_module__c4cd3e_idx',
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
    ]
