# Generated by Django 6.0.4 on 2026-06-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_delete_coursecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresource',
            name='metadata',
        ),
    ]
