# Generated by Django 6.0.4 on 2026-06-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_lessonresource_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonresource',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
