# Generated by Django 6.0.4 on 2026-05-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_coursecontent_is_inline_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecontent',
            name='text_content',
            field=models.TextField(blank=True, help_text='Plain text or HTML for text items.'),
        ),
        migrations.AlterField(
            model_name='module',
            name='body_content',
            field=models.TextField(help_text="Plain text or HTML. Use <span class='highlight-link' data-content-id='ID'>text</span> to add interactive highlights."),
        ),
    ]
