# Generated by Django 6.0.4 on 2026-05-17 01:27

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def create_missing_category_tables(apps, schema_editor):
    """Create Category/Subcategory tables only if they don't already exist."""
    from content.models import Category, Subcategory

    existing_tables = set(schema_editor.connection.introspection.table_names())

    if Category._meta.db_table not in existing_tables:
        schema_editor.create_model(Category)

    existing_tables = set(schema_editor.connection.introspection.table_names())
    if Subcategory._meta.db_table not in existing_tables:
        schema_editor.create_model(Subcategory)


def drop_category_tables_if_exist(apps, schema_editor):
    from content.models import Category, Subcategory

    existing_tables = set(schema_editor.connection.introspection.table_names())

    if Subcategory._meta.db_table in existing_tables:
        schema_editor.delete_model(Subcategory)

    existing_tables = set(schema_editor.connection.introspection.table_names())
    if Category._meta.db_table in existing_tables:
        schema_editor.delete_model(Category)


def _table_columns(connection, table_name):
    with connection.cursor() as cursor:
        return {col.name for col in connection.introspection.get_table_description(cursor, table_name)}


def _create_category_with_legacy_support(apps, schema_editor):
    Category = apps.get_model('content', 'Category')
    connection = schema_editor.connection

    try:
        return Category.objects.create(name='General', slug='general')
    except Exception:
        cols = _table_columns(connection, Category._meta.db_table)
        column_names = ['name', 'slug']
        values = ['General', 'general']

        if 'description' in cols:
            column_names.append('description')
            values.append('General category')
        if 'created_at' in cols:
            column_names.append('created_at')
            values.append(timezone.now())

        qn = connection.ops.quote_name
        placeholders = ', '.join(['%s'] * len(values))
        with connection.cursor() as cursor:
            cursor.execute(
                f"INSERT INTO {qn(Category._meta.db_table)} ({', '.join(qn(c) for c in column_names)}) VALUES ({placeholders})",
                values,
            )
        return Category.objects.get(slug='general')


def _create_subcategory_with_legacy_support(apps, schema_editor, category):
    Subcategory = apps.get_model('content', 'Subcategory')
    connection = schema_editor.connection

    try:
        return Subcategory.objects.create(category=category, name='Bangla', slug='bangla')
    except Exception:
        cols = _table_columns(connection, Subcategory._meta.db_table)
        column_names = ['category_id', 'name', 'slug']
        values = [category.id, 'Bangla', 'bangla']

        if 'description' in cols:
            column_names.append('description')
            values.append('Default subcategory')
        if 'created_at' in cols:
            column_names.append('created_at')
            values.append(timezone.now())

        qn = connection.ops.quote_name
        placeholders = ', '.join(['%s'] * len(values))
        with connection.cursor() as cursor:
            cursor.execute(
                f"INSERT INTO {qn(Subcategory._meta.db_table)} ({', '.join(qn(c) for c in column_names)}) VALUES ({placeholders})",
                values,
            )
        return Subcategory.objects.filter(category_id=category.id, slug='bangla').order_by('id').first()


def assign_default_subcategory(apps, schema_editor):
    Course = apps.get_model('content', 'Course')
    Category = apps.get_model('content', 'Category')
    Subcategory = apps.get_model('content', 'Subcategory')

    default_subcategory = Subcategory.objects.order_by('id').first()
    if default_subcategory is None:
        default_category = Category.objects.order_by('id').first() or _create_category_with_legacy_support(apps, schema_editor)
        default_subcategory = _create_subcategory_with_legacy_support(apps, schema_editor, default_category)

    if default_subcategory is None:
        raise RuntimeError('Could not create or find a default subcategory for existing courses.')

    Course.objects.filter(subcategory__isnull=True).update(subcategory=default_subcategory)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_coursecontent_text_content_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Category',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('slug', models.SlugField(unique=True)),
                    ],
                    options={
                        'ordering': ['name'],
                    },
                ),
                migrations.CreateModel(
                    name='Subcategory',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=255)),
                        ('slug', models.SlugField()),
                        ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='content.category')),
                    ],
                    options={
                        'ordering': ['name'],
                        'unique_together': {('category', 'slug')},
                    },
                ),
            ],
            database_operations=[
                migrations.RunPython(create_missing_category_tables, reverse_code=drop_category_tables_if_exist),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.subcategory'),
        ),
        migrations.RunPython(assign_default_subcategory, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='content.subcategory'),
        ),
    ]
