# Generated by Django 6.0.4 on 2026-05-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_category_subcategory_existing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
