# Generated by Django 6.0.4 on 2026-07-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_alter_category_slug_alter_course_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursequiz',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='coursequiz',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modulepurchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinstruction',
            name='payment_method_name',
            field=models.CharField(blank=True, choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], default='other', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentsubmission',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='ModuleAccordionSection',
        ),
    ]
