# Generated by Django 6.0.4 on 2026-05-17 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_lms_architecture_refactor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentinstruction',
            options={'ordering': ['payment_method_name', '-created_at']},
        ),
        migrations.RenameIndex(
            model_name='coursecontent',
            new_name='content_cou_module__c4cd3e_idx',
            old_name='content_cour_module__23b1f6_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='content_cou_user_id_c935b5_idx',
            old_name='content_cour_user_id_cf1b42_idx',
        ),
        migrations.RenameIndex(
            model_name='courseenrollment',
            new_name='content_cou_course__f998d0_idx',
            old_name='content_cour_course__7afd74_idx',
        ),
        migrations.RenameIndex(
            model_name='coursequiz',
            new_name='content_cou_lesson__7adaa0_idx',
            old_name='content_cour_lesson__8238cc_idx',
        ),
        migrations.RenameIndex(
            model_name='coursequiz',
            new_name='content_cou_module__33370f_idx',
            old_name='content_cour_module__a94858_idx',
        ),
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='content_ema_user_id_05a6dd_idx',
            old_name='content_emai_user_id_240ef7_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='content_les_module__c210ff_idx',
            old_name='content_less_module__2cf218_idx',
        ),
        migrations.RenameIndex(
            model_name='lesson',
            new_name='content_les_module__dffc17_idx',
            old_name='content_less_module__e61801_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonresource',
            new_name='content_les_lesson__aeba6e_idx',
            old_name='content_less_lesson__12ab8e_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonresource',
            new_name='content_les_lesson__0e9f15_idx',
            old_name='content_less_lesson__193958_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonresource',
            new_name='content_les_lesson__f4dd6b_idx',
            old_name='content_less_lesson__731c1c_idx',
        ),
        migrations.RenameIndex(
            model_name='module',
            new_name='content_mod_course__07037a_idx',
            old_name='content_modu_course__1821f4_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsubmission',
            new_name='content_pay_course__82b52b_idx',
            old_name='content_paym_course__00fdfe_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsubmission',
            new_name='content_pay_user_id_05b417_idx',
            old_name='content_paym_user_id_cb8760_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentsubmission',
            new_name='content_pay_transac_8cbe04_idx',
            old_name='content_paym_transac_76f2c9_idx',
        ),
        migrations.RenameIndex(
            model_name='quizattempt',
            new_name='content_qui_user_id_58b769_idx',
            old_name='content_quiz_user_id_3399c3_idx',
        ),
        migrations.RenameIndex(
            model_name='studentdevicesession',
            new_name='content_stu_user_id_43ddca_idx',
            old_name='content_stud_user_id_0dfa25_idx',
        ),
        migrations.AlterField(
            model_name='coursequiz',
            name='pass_score',
            field=models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='modulepurchase',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_purchases', to='content.course'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddIndex(
            model_name='modulepurchase',
            index=models.Index(fields=['user', 'is_purchased'], name='content_mod_user_id_48a93a_idx'),
        ),
    ]
