# Generated by Django 6.0.4 on 2026-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_alter_paymentinstruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_categories',
            field=models.ManyToManyField(blank=True, help_text='Categories that this teacher is allowed to manage.', related_name='assigned_teachers', to='content.category'),
        ),
    ]
