# Generated by Django 6.0.4 on 2026-07-12 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailOTP',
            new_name='OTP',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='authenticat_user_id_8202b7_idx',
            old_name='authenticat_user_id_20832e_idx',
        ),
    ]
